### ISSUE TITLE
Error when launch ardrone.vislab.launch

### ISSUE THREAD

**Issue by tngan** [vislab-tecnico-lisboa/ardrone_gazebo#3]
`catkin_make` runs successfully. After that, I try to launch the ardrone.vislab.launch, but the following error is shown.

```
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/xacro/xacro.py", line 55, in <module>
    import xacro
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/xacro/__init__.py", line 42, in <module>
    from roslaunch import substitution_args
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 56, in <module>
    from .launch import ROSLaunchRunner
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/launch.py", line 55, in <module>
    from roslaunch.nodeprocess import create_master_process, create_node_process
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/nodeprocess.py", line 52, in <module>
    from rosmaster.master_api import NUM_WORKERS
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosmaster/__init__.py", line 35, in <module>
    from .main import rosmaster_main
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosmaster/main.py", line 43, in <module>
    import rosmaster.master
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosmaster/master.py", line 47, in <module>
    import rosmaster.master_api
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 72, in <module>
    from rosmaster.util import xmlrpcapi
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosmaster/util.py", line 48, in <module>
    from defusedxml.xmlrpc import monkey_patch
ImportError: No module named defusedxml.xmlrpc
while processing /home/tngan/catkin_ws/src/ardrone_gazebo/ardrone_vislab/ardrone_vislab_gazebo/launch/spawn_quadrotor.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/kinetic/share/xacro/xacro.py '/home/tngan/catkin_ws/src/ardrone_gazebo/ardrone_vislab/ardrone_vislab_description/urdf/quadrotor_sensors.urdf.xacro'] returned with code [1]. 

Param xml is <param command="$(find xacro)/xacro.py '$(arg model)'" name="robot_description"/>
The traceback for the exception was written to the log file
```

I am using ROS kinetic and gazebo 7.

**Comment by nigno17** [comment]
can you please check if you have this package installed? 
python-defusedxml

**Comment by tngan** [comment]
@nigno17 Yes, I have installed it. Cool, I just discovered my $PYTHONPATH is not set properly, and the issue solved and I can run the simulator now.

**Comment by tngan** [comment]
However, I got another problem.

```
redefining global property: pi
when processing file: /home/tngan/catkin_ws/src/ardrone_gazebo/ardrone_vislab/ardrone_vislab_description/urdf/quadrotor_base.urdf.xacro
included from: /home/tngan/catkin_ws/src/ardrone_gazebo/ardrone_vislab/ardrone_vislab_description/urdf/quadrotor_sensors.urdf.xacro
inconsistent namespace redefinitions for xmlns:xacro:
 old: http://playerstage.sourceforge.net/gazebo/xmlschema/#interface
 new: http://ros.org/wiki/xacro (/home/tngan/catkin_ws/src/ardrone_gazebo/ardrone_vislab/ardrone_vislab_description/urdf/quadrotor_base.urdf.xacro)
inconsistent namespace redefinitions for xmlns:xacro:
 old: http://playerstage.sourceforge.net/gazebo/xmlschema/#interface
 new: http://ros.org/wiki/xacro (/home/tngan/catkin_ws/src/ardrone_gazebo/ardrone_vislab/ardrone_vislab_description/urdf/sensors/sonar_sensor.urdf.xacro)
inconsistent namespace redefinitions for xmlns:xacro:
 old: http://playerstage.sourceforge.net/gazebo/xmlschema/#interface
 new: http://ros.org/wiki/xacro (/home/tngan/catkin_ws/src/ardrone_gazebo/ardrone_vislab/ardrone_vislab_description/urdf/sensors/generic_camera.urdf.xacro)
inconsistent namespace redefinitions for xmlns:xacro:
 old: http://playerstage.sourceforge.net/gazebo/xmlschema/#interface
 new: http://ros.org/wiki/xacro (/home/tngan/catkin_ws/src/ardrone_gazebo/ardrone_vislab/ardrone_vislab_description/urdf/sensors/generic_camera.urdf.xacro)
```

The map is successfully shown in Gazebo but no quadcopter model, and no messages in /ardrone/image_raw topic is being published.

The last message is shown as follow.

```
[INFO] : Waiting for service /gazebo/spawn_urdf_model
```

**Comment by nigno17** [comment]
The warning messages that you are showing should not be a problem.  Can you post the log messages that you find in ~/.ros/log/latest ? Which is the output of "rostopic list" ?

**Comment by tngan** [comment]
**Result of rostopic list**

```
/ardrone/aruco/pose
/ardrone/image_raw
/clock
/ground_truth/state
/joint_states
/rosout
/rosout_agg
/tf
/tf_static
```

and there is no publisher for the topic `/ardrone/image_raw`.

**Comment by tngan** [comment]
**roslaunch log**

```
[roslaunch][INFO] 2017-03-18 11:29:17,321: Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
[roslaunch][INFO] 2017-03-18 11:29:17,325: Done checking log file disk usage. Usage is <1GB.
[roslaunch][INFO] 2017-03-18 11:29:17,325: roslaunch starting with args ['/opt/ros/kinetic/bin/roslaunch', 'aruco_test', 'aruco_test.launch']
[roslaunch][INFO] 2017-03-18 11:29:17,325: roslaunch env is {'_': '/opt/ros/kinetic/bin/roslaunch', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'ROS_DISTRO': 'kinetic', '_VIRTUALENVWRAPPER_API': ' mkvirtualenv rmvirtualenv lsvirtualenv showvirtualenv workon add2virtualenv cdsitepackages cdvirtualenv lssitepackages toggleglobalsitepackages cpvirtualenv setvirtualenvproject mkproject cdproject mktmpenv wipeenv allvirtualenv', 'ROS_LOG_FILENAME': '/home/tngan/.ros/log/ea8e7664-0b8a-11e7-a6e5-54271e204e11/roslaunch-tngan-bot-8177.log', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/tngan', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'PKG_CONFIG_PATH': '/home/tngan/catkin_ws/devel/lib/pkgconfig:/opt/ros/kinetic/lib/pkgconfig:/usr/local/lib/pkgconfig', 'UPSTART_EVENTS': 'xsession started', 'XDG_CURRENT_DESKTOP': 'Unity', 'GNOME_KEYRING_PID': '', 'XDG_SESSION_TYPE': 'x11', 'ROSLISP_PACKAGE_DIRECTORIES': '/home/tngan/catkin_ws/devel/share/common-lisp', 'QT_IM_MODULE': 'ibus', 'LOGNAME': 'tngan', 'WINDOWID': '58720260', 'PATH': '/opt/ros/kinetic/bin:/home/tngan/.pyenv/shims:/home/tngan/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'XDG_VTNR': '7', 'GNOME_KEYRING_CONTROL': '', 'VIRTUALENVWRAPPER_SCRIPT': '/usr/local/bin/virtualenvwrapper.sh', 'LD_LIBRARY_PATH': '/home/tngan/catkin_ws/devel/lib:/opt/ros/kinetic/lib', 'XDG_SESSION_DESKTOP': 'ubuntu', 'LANG': 'en_HK.UTF-8', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'XAUTHORITY': '/home/tngan/.Xauthority', 'PYENV_SHELL': 'bash', 'SESSION_MANAGER': 'local/tngan-bot:@/tmp/.ICE-unix/5619,unix/tngan-bot:/tmp/.ICE-unix/5619', 'SHLVL': '1', 'XDG_SESSION_ID': 'c2', 'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'TERMINATOR_UUID': 'urn:uuid:bcde21bd-f5d9-475c-8fdd-3985527f7460', 'QT_ACCESSIBILITY': '1', 'ROS_ETC_DIR': '/opt/ros/kinetic/etc/ros', 'DISPLAY': ':0', 'UPSTART_INSTANCE': '', 'CLUTTER_IM_MODULE': 'xim', 'SESSION': 'ubuntu', 'SESSIONTYPE': 'gnome-session', 'VIRTUALENVWRAPPER_PYTHON': '/usr/bin/python', 'XMODIFIERS': '@im=ibus', 'GIO_LAUNCHED_DESKTOP_FILE_PID': '6514', 'GPG_AGENT_INFO': '/home/tngan/.gnupg/S.gpg-agent:0:1', 'HOME': '/home/tngan', 'QT4_IM_MODULE': 'xim', 'GTK2_MODULES': 'overlay-scrollbar', 'WORKON_HOME': '/home/tngan/.virtualenvs', 'GIO_LAUNCHED_DESKTOP_FILE': '/usr/share/applications/terminator.desktop', 'CMAKE_PREFIX_PATH': '/home/tngan/catkin_ws/devel:/opt/ros/kinetic', 'XDG_RUNTIME_DIR': '/run/user/1000', 'INSTANCE': '', 'PYTHONPATH': '/home/tngan/catkin_ws/devel/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages', 'COMPIZ_CONFIG_PROFILE': 'ubuntu', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'ROS_ROOT': '/opt/ros/kinetic/share/ros', 'GDMSESSION': 'ubuntu', 'IM_CONFIG_PHASE': '1', 'UPSTART_JOB': 'unity7', 'IBUS_DISABLE_SNOOPER': '1', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'ROS_PACKAGE_PATH': '/home/tngan/catkin_ws/src:/opt/ros/kinetic/share', 'LANGUAGE': 'en_HK:en', 'ARUCO_LIB_PATH': '/home/tngan/Desktop/aruco-2.0.10', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-hJ7FW28Qv4', 'ORBIT_SOCKETDIR': '/tmp/orbit-tngan', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'GTK_IM_MODULE': 'ibus', 'DESKTOP_SESSION': 'ubuntu', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/5389', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg', 'GTK_MODULES': 'gail:atk-bridge:unity-gtk-module', 'XDG_SEAT': 'seat0', 'GDM_LANG': 'en_US', 'PYENV_ROOT': '/home/tngan/.pyenv', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop', 'PWD': '/home/tngan', 'JOB': 'unity-settings-daemon', 'ROS_MASTER_URI': 'http://localhost:11311', 'COLORTERM': 'gnome-terminal', 'QT_LINUX_ACCESSIBILITY_ALWAYS_ON': '1', 'XDG_MENU_PREFIX': 'gnome-', 'COMPIZ_BIN_PATH': '/usr/bin/', 'USER': 'tngan'}
[roslaunch][INFO] 2017-03-18 11:29:17,325: starting in server mode
[roslaunch.parent][INFO] 2017-03-18 11:29:17,325: starting roslaunch parent run
[roslaunch][INFO] 2017-03-18 11:29:17,325: loading roscore config file /opt/ros/kinetic/etc/ros/roscore.xml
[roslaunch][INFO] 2017-03-18 11:29:17,461: Added core node of type [rosout/rosout] in namespace [/]
[roslaunch.config][INFO] 2017-03-18 11:29:17,461: loading config file /home/tngan/catkin_ws/src/ardrone_gazebo/aruco_test/launch/aruco_test.launch
[roslaunch][INFO] 2017-03-18 11:29:17,535: Added node of type [aruco_test/aruco_test] in namespace [/]
[roslaunch][INFO] 2017-03-18 11:29:17,536: ... selected machine [] for node of type [aruco_test/aruco_test]
[roslaunch.pmon][INFO] 2017-03-18 11:29:17,536: start_process_monitor: creating ProcessMonitor
[roslaunch.pmon][INFO] 2017-03-18 11:29:17,536: created process monitor <ProcessMonitor(ProcessMonitor-1, initial daemon)>
[roslaunch.pmon][INFO] 2017-03-18 11:29:17,537: start_process_monitor: ProcessMonitor started
[roslaunch.parent][INFO] 2017-03-18 11:29:17,537: starting parent XML-RPC server
[roslaunch.server][INFO] 2017-03-18 11:29:17,537: starting roslaunch XML-RPC server
[roslaunch.server][INFO] 2017-03-18 11:29:17,537: waiting for roslaunch XML-RPC server to initialize
[xmlrpc][INFO] 2017-03-18 11:29:17,537: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-03-18 11:29:17,537: Started XML-RPC server [http://tngan-bot:46288/]
[xmlrpc][INFO] 2017-03-18 11:29:17,537: xml rpc node: starting XML-RPC server
[roslaunch][INFO] 2017-03-18 11:29:17,549: started roslaunch server http://tngan-bot:46288/
[roslaunch.parent][INFO] 2017-03-18 11:29:17,549: ... parent XML-RPC server started
[roslaunch][INFO] 2017-03-18 11:29:17,550: master.is_running[http://localhost:11311]
[roslaunch][INFO] 2017-03-18 11:29:17,551: master.is_running[http://localhost:11311]
[roslaunch][INFO] 2017-03-18 11:29:17,552: ROS_MASTER_URI=http://localhost:11311
[roslaunch][INFO] 2017-03-18 11:29:17,553: setting /roslaunch/uris/host_tngan_bot__46288' to http://tngan-bot:46288/
[roslaunch][INFO] 2017-03-18 11:29:17,555: load_parameters starting ...
[roslaunch][INFO] 2017-03-18 11:29:17,557: ... load_parameters complete
[roslaunch][INFO] 2017-03-18 11:29:17,557: launch_nodes: launching local nodes ...
[roslaunch][INFO] 2017-03-18 11:29:17,557: ... preparing to launch node of type [aruco_test/aruco_test]
[roslaunch][INFO] 2017-03-18 11:29:17,557: create_node_process: package[aruco_test] type[aruco_test] machine[Machine(name[] env_loader[None] address[localhost] ssh_port[22] user[None] assignable[True] timeout[10.0])] master_uri[http://localhost:11311]
[roslaunch][INFO] 2017-03-18 11:29:17,557: process[aruco_test_node-1]: env[{'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'ROS_DISTRO': 'kinetic', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/tngan', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'IBUS_DISABLE_SNOOPER': '1', 'UPSTART_EVENTS': 'xsession started', 'XDG_CURRENT_DESKTOP': 'Unity', 'XDG_SESSION_TYPE': 'x11', 'ROSLISP_PACKAGE_DIRECTORIES': '/home/tngan/catkin_ws/devel/share/common-lisp', 'QT_IM_MODULE': 'ibus', 'LOGNAME': 'tngan', 'XDG_SEAT': 'seat0', 'PATH': '/opt/ros/kinetic/bin:/home/tngan/.pyenv/shims:/home/tngan/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'XDG_VTNR': '7', 'GNOME_KEYRING_CONTROL': '', 'ROS_PACKAGE_PATH': '/home/tngan/catkin_ws/src:/opt/ros/kinetic/share', 'VIRTUALENVWRAPPER_SCRIPT': '/usr/local/bin/virtualenvwrapper.sh', 'LD_LIBRARY_PATH': '/home/tngan/catkin_ws/devel/lib:/opt/ros/kinetic/lib', 'XDG_SESSION_DESKTOP': 'ubuntu', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'XAUTHORITY': '/home/tngan/.Xauthority', 'PYENV_SHELL': 'bash', 'SESSION_MANAGER': 'local/tngan-bot:@/tmp/.ICE-unix/5619,unix/tngan-bot:/tmp/.ICE-unix/5619', 'SHLVL': '1', 'ARUCO_LIB_PATH': '/home/tngan/Desktop/aruco-2.0.10', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'TERMINATOR_UUID': 'urn:uuid:bcde21bd-f5d9-475c-8fdd-3985527f7460', 'CLUTTER_IM_MODULE': 'xim', 'ROS_LOG_FILENAME': '/home/tngan/.ros/log/ea8e7664-0b8a-11e7-a6e5-54271e204e11/roslaunch-tngan-bot-8177.log', 'UPSTART_INSTANCE': '', 'QT_ACCESSIBILITY': '1', 'WINDOWID': '58720260', 'ORBIT_SOCKETDIR': '/tmp/orbit-tngan', 'SESSIONTYPE': 'gnome-session', 'XMODIFIERS': '@im=ibus', '_VIRTUALENVWRAPPER_API': ' mkvirtualenv rmvirtualenv lsvirtualenv showvirtualenv workon add2virtualenv cdsitepackages cdvirtualenv lssitepackages toggleglobalsitepackages cpvirtualenv setvirtualenvproject mkproject cdproject mktmpenv wipeenv allvirtualenv', 'GPG_AGENT_INFO': '/home/tngan/.gnupg/S.gpg-agent:0:1', 'HOME': '/home/tngan', 'QT4_IM_MODULE': 'xim', 'PYENV_ROOT': '/home/tngan/.pyenv', 'GTK2_MODULES': 'overlay-scrollbar', 'LANG': 'en_HK.UTF-8', 'GIO_LAUNCHED_DESKTOP_FILE': '/usr/share/applications/terminator.desktop', 'CMAKE_PREFIX_PATH': '/home/tngan/catkin_ws/devel:/opt/ros/kinetic', 'XDG_RUNTIME_DIR': '/run/user/1000', 'WORKON_HOME': '/home/tngan/.virtualenvs', 'GTK_IM_MODULE': 'ibus', 'PYTHONPATH': '/home/tngan/catkin_ws/devel/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages', 'COMPIZ_CONFIG_PROFILE': 'ubuntu', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'GTK_MODULES': 'gail:atk-bridge:unity-gtk-module', 'ROS_ROOT': '/opt/ros/kinetic/share/ros', 'GDMSESSION': 'ubuntu', 'IM_CONFIG_PHASE': '1', 'UPSTART_JOB': 'unity7', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'GIO_LAUNCHED_DESKTOP_FILE_PID': '6514', 'PKG_CONFIG_PATH': '/home/tngan/catkin_ws/devel/lib/pkgconfig:/opt/ros/kinetic/lib/pkgconfig:/usr/local/lib/pkgconfig', 'VIRTUALENVWRAPPER_PYTHON': '/usr/bin/python', 'XDG_SESSION_ID': 'c2', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-hJ7FW28Qv4', '_': '/opt/ros/kinetic/bin/roslaunch', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'SESSION': 'ubuntu', 'DESKTOP_SESSION': 'ubuntu', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/5389', 'DISPLAY': ':0', 'GNOME_KEYRING_PID': '', 'GDM_LANG': 'en_US', 'LANGUAGE': 'en_HK:en', 'INSTANCE': '', 'PWD': '/home/tngan', 'JOB': 'unity-settings-daemon', 'ROS_ETC_DIR': '/opt/ros/kinetic/etc/ros', 'ROS_MASTER_URI': 'http://localhost:11311', 'COLORTERM': 'gnome-terminal', 'QT_LINUX_ACCESSIBILITY_ALWAYS_ON': '1', 'XDG_MENU_PREFIX': 'gnome-', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg', 'COMPIZ_BIN_PATH': '/usr/bin/', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop', 'USER': 'tngan'}]
[roslaunch][INFO] 2017-03-18 11:29:17,609: process[aruco_test_node-1]: args[[u'/home/tngan/catkin_ws/devel/lib/aruco_test/aruco_test', u'__name:=aruco_test_node']]
[roslaunch][INFO] 2017-03-18 11:29:17,609: ... created process [aruco_test_node-1]
[roslaunch.pmon][INFO] 2017-03-18 11:29:17,609: ProcessMonitor.register[aruco_test_node-1]
[roslaunch.pmon][INFO] 2017-03-18 11:29:17,609: ProcessMonitor.register[aruco_test_node-1] complete
[roslaunch][INFO] 2017-03-18 11:29:17,609: ... registered process [aruco_test_node-1]
[roslaunch][INFO] 2017-03-18 11:29:17,609: process[aruco_test_node-1]: starting os process
[roslaunch][INFO] 2017-03-18 11:29:17,610: process[aruco_test_node-1]: start w/ args [[u'/home/tngan/catkin_ws/devel/lib/aruco_test/aruco_test', u'__name:=aruco_test_node', u'__log:=/home/tngan/.ros/log/ea8e7664-0b8a-11e7-a6e5-54271e204e11/aruco_test_node-1.log']]
[roslaunch][INFO] 2017-03-18 11:29:17,610: process[aruco_test_node-1]: cwd will be [/home/tngan/.ros]
[roslaunch][INFO] 2017-03-18 11:29:17,627: process[aruco_test_node-1]: started with pid [8255]
[roslaunch][INFO] 2017-03-18 11:29:17,627: ... successfully launched [aruco_test_node-1]
[roslaunch][INFO] 2017-03-18 11:29:17,627: ... launch_nodes complete
[roslaunch.pmon][INFO] 2017-03-18 11:29:17,627: registrations completed <ProcessMonitor(ProcessMonitor-1, started daemon 140346201229056)>
[roslaunch.parent][INFO] 2017-03-18 11:29:17,628: ... roslaunch parent running, waiting for process exit
[roslaunch][INFO] 2017-03-18 11:29:17,628: spin
```

**spawn_robot.log**

```
[rospy.client][INFO] 2017-03-18 11:28:47,435: init_node, name[/spawn_robot], pid[7404]
[xmlrpc][INFO] 2017-03-18 11:28:47,435: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-03-18 11:28:47,435: Started XML-RPC server [http://tngan-bot:34960/]
[rospy.init][INFO] 2017-03-18 11:28:47,435: ROS Slave URI: [http://tngan-bot:34960/]
[rospy.impl.masterslave][INFO] 2017-03-18 11:28:47,435: _ready: http://tngan-bot:34960/
[xmlrpc][INFO] 2017-03-18 11:28:47,436: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-03-18 11:28:47,436: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-03-18 11:28:47,536: registered with master
[rospy.rosout][INFO] 2017-03-18 11:28:47,536: initializing /rosout core topic
[rospy.rosout][INFO] 2017-03-18 11:28:47,538: connected to core topic /rosout
[rospy.simtime][INFO] 2017-03-18 11:28:47,539: initializing /clock core topic
[rospy.simtime][INFO] 2017-03-18 11:28:47,540: connected to core topic /clock
[rosout][INFO] 2017-03-18 11:28:47,542: Loading model XML from ros parameter
[rosout][INFO] 2017-03-18 11:28:47,545: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2017-03-18 11:28:47,826: topic[/rosout] adding connection to [/rosout], count 0
```

**Comment by nigno17** [comment]
I cannot reproduce your problem (not spawning the drone) on my machines here. Do you have the latest version of the repository installed? if not could you please try to update it and see if the problem persist?
